using Takupoke.Core.Recovery;
using Takupoke.Infrastructure.Recovery;
using Xunit;

namespace Takupoke.Integration.Tests;

public sealed class OcrInputTransformTests
{
    [Theory]
    [InlineData(30, 20, 72, 320)]
    [InlineData(69, 10, 331, 331)]
    [InlineData(200, 20, 480, 480)]
    [InlineData(200, 10, 960, 960)]
    [InlineData(1, 4096, 1, 320)]
    public void ReferenceWidthsAndNormalizedZeroPadding(int width, int height, int validWidth, int inputWidth)
    {
        var input = OcrInputTransform.Recognition(Solid(width, height, 0, 127, 255), new(0, 0, width, height));
        Assert.Equal(validWidth, input.ValidWidth); Assert.Equal(inputWidth, input.InputWidth);
        Assert.Equal(new[] { 1, 3, 48, inputWidth }, input.Tensor.Dimensions.ToArray());
        for (var y = 0; y < 48; y++)
        {
            Assert.Equal(-1f, input.Tensor[0, 0, y, 0]);
            Assert.Equal((127f / 255f - .5f) / .5f, input.Tensor[0, 1, y, validWidth - 1]);
            Assert.Equal(1f, input.Tensor[0, 2, y, validWidth - 1]);
            for (var x = validWidth; x < inputWidth; x++) for (var c = 0; c < 3; c++) Assert.Equal(0f, input.Tensor[0, c, y, x]);
        }
    }

    [Fact]
    public void RecognitionMatchesIndependentOpenCvLinearSamplesWithinOneByte()
    {
        // Generated by the actual PaddleX 917f10be OCRReisizeNormImg class
        // with OpenCV 4.11.0. Values are resized uint8 BGR, before normalization.
        byte[] source = [0, 11, 253, 255, 91, 177, 33, 255, 255, 68, 109, 255,
            210, 37, 3, 255, 17, 249, 129, 255, 74, 4, 241, 255];
        var input = OcrInputTransform.Recognition(new(3, 2, source), new(0, 0, 3, 2));
        Assert.Equal(72, input.ValidWidth); Assert.Equal(320, input.InputWidth);
        int[] xs = [0, 1, 15, 23, 24, 25, 46, 47, 48, 70, 71], ys = [0, 12, 23, 24, 35, 47];
        var bytes = Convert.FromBase64String("AAv9AAv9DSPdK1qTL2GKM2iBo4FCqX1FsHhJ/0Rt/0RtBAz4BAz4ESTYLVuSMWKJNGmAoIFEp31IrXhL+0Nw+0NwZReFZReFXjN9T3FrTXlpS4FnaYd4bYB7cnl/qCWsqCWsbRl7bRl7ZTR1UnNoUHtmTYNkZIh8aICAbXmEoSOyoSOyziQIziQIskMZdIlBbJJGZJtLLI2wL4O0MXm5TgXuTgXu0iUD0iUDtkQVdYo/bZNFZZxKKo6yLIS2L3m7SgTxSgTx");
        Assert.Equal(xs.Length * ys.Length * 3, bytes.Length);
        var i = 0;
        foreach (var y in ys) foreach (var x in xs) for (var c = 0; c < 3; c++)
        {
            var expected = (bytes[i++] / 255f - .5f) / .5f;
            Assert.InRange(Math.Abs(input.Tensor[0, c, y, x] - expected), 0f, 2f / 255f + 1e-6f);
        }
    }

    [Fact]
    public void DetectionUsesBgrLinearSamplingAndExistingNormalization()
    {
        byte[] source = [0, 10, 20, 255, 100, 110, 120, 255, 200, 210, 220, 255];
        var tensor = OcrInputTransform.Detection(new(3, 1, source), new(0, 0, 3, 1), 6, 1);
        // Independent OpenCV INTER_LINEAR 3->6 samples: 0,25,75,125,175,200.
        int[] expected = [0, 25, 75, 125, 175, 200];
        float[] mean = [.485f, .456f, .406f], std = [.229f, .224f, .225f];
        for (var x = 0; x < 6; x++) for (var c = 0; c < 3; c++)
            Assert.InRange(Math.Abs(tensor[0, c, 0, x] - ((expected[x] + c * 10) / 255f - mean[c]) / std[c]), 0f, 1e-6f);
    }

    [Fact]
    public void CtcTimeCoordinatesInvertPaddingAndRejectUnsupportedIntervals()
    {
        var crop = new RecoveryBox(10, 5, 30, 20);
        var input = OcrInputTransform.Recognition(Solid(50, 30, 255, 255, 255), crop);
        // 80 time steps cover 320 tensor pixels. Frames9..18 cover source
        // pixels36..72 of the valid72-pixel resize: the crop's right half.
        Assert.Equal(new RecoveryBox(25, 5, 15, 20), input.SourceBox(9, 18, 80));
        Assert.Equal(crop, input.SourceBox(0, 18, 80));
        Assert.Throws<InvalidDataException>(() => input.SourceBox(17, 19, 80));
        Assert.Throws<InvalidDataException>(() => input.SourceBox(19, 20, 80));
        Assert.Throws<InvalidDataException>(() => input.SourceBox(-1, 1, 80));
        Assert.Throws<InvalidDataException>(() => input.SourceBox(1, 1, 80));
        Assert.Throws<InvalidDataException>(() => input.SourceBox(0, 1, 0));
        Assert.Throws<InvalidDataException>(() => input.SourceBox(0, 81, 80));
    }

    [Fact]
    public void UnpaddedCtcCoordinatesKeepOriginalFractionalCrop()
    {
        var crop = new RecoveryBox(.6, .6, 20, 1);
        var input = OcrInputTransform.Recognition(Solid(22, 3, 255, 255, 255), crop);
        Assert.Equal(960, input.InputWidth); Assert.Equal(960, input.ValidWidth);
        var box = input.SourceBox(12, 24, 48);
        Assert.Equal(5.6, box.X, 10); Assert.Equal(5, box.Width, 10);
        Assert.Equal(crop.Y, box.Y); Assert.Equal(crop.Height, box.Height); Assert.True(crop.Contains(box));
    }

    [Fact]
    public void FractionalCropNeverSamplesNeighborPixelCentres()
    {
        var image = Solid(3, 3, 255, 255, 255);
        Array.Clear(image.Bgra, (1 * 3 + 1) * 4, 3);
        var input = OcrInputTransform.Recognition(image, new(.6, .6, 1.3, 1.3));
        for (var c = 0; c < 3; c++) for (var y = 0; y < 48; y++) for (var x = 0; x < input.ValidWidth; x++)
            Assert.Equal(-1f, input.Tensor[0, c, y, x]);
        Assert.Throws<InvalidDataException>(() => OcrInputTransform.Recognition(image, new(.6, .6, .1, .1)));
        Assert.Throws<InvalidDataException>(() => OcrInputTransform.Recognition(image, new(-.1, 0, 1, 1)));
        Assert.Throws<InvalidDataException>(() => OcrInputTransform.Recognition(image, new(2, 0, 2, 1)));
    }

    [Fact]
    public void CapacityAndCancellationFailBeforeReturningInput()
    {
        Assert.Throws<InvalidDataException>(() => OcrInputTransform.Recognition(Solid(201, 10, 0, 0, 0), new(0, 0, 201, 10)));
        Assert.Throws<InvalidDataException>(() => OcrInputTransform.Detection(Solid(1, 1, 0, 0, 0), new(0, 0, 1, 1), 1024, 32));
        using var cancel = new CancellationTokenSource(); cancel.Cancel();
        Assert.Throws<OperationCanceledException>(() => OcrInputTransform.Recognition(Solid(1, 1, 0, 0, 0), new(0, 0, 1, 1), cancel.Token));
        Assert.Throws<OperationCanceledException>(() => OcrInputTransform.Detection(Solid(1, 1, 0, 0, 0), new(0, 0, 1, 1), 32, 32, cancel.Token));
    }

    private static RecoveryRaster Solid(int width, int height, byte blue, byte green, byte red)
    {
        var bytes = new byte[width * height * 4];
        for (var i = 0; i < bytes.Length; i += 4) { bytes[i] = blue; bytes[i + 1] = green; bytes[i + 2] = red; bytes[i + 3] = 255; }
        return new(width, height, bytes);
    }
}
